In [2]:
import numpy as np

liste = [1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300]

# Créer un array que vous nommerez revenus
revenus = np.array(liste)
print("Array :", revenus)

# Créer un nouvel array haut_revenus dans lequel vous sélectionnerez l'ensemble des revenus supérieurs ou égal à 3000€
haut_revenus = revenus[revenus >= 3_000]
print("Ensemble des revenus supérieurs ou égal à 3000€: ", haut_revenus)

# calculer la somme des revenus annuelle. Pour rappel, les revenus listés ci dessus sont mensuels.
somme = revenus.sum() * 12
print("La somme des revenus annuelle est:", somme, "€")

somme_k = round(somme / 1000)
print("La somme des revenus annuelle est:", somme_k, "K€")

somme_m = round((somme / 1_000_000), 2)
print("La somme des revenus annuelle est:", somme_m, "M€")

# calculer la moyenne des revenus des 10 clients
moyenne = revenus.mean()
print("La moyenne des revenus mensuelle est:", moyenne, "€")

# Un de nos clients (dont les revenus mensuels s'élevaient jusque là à 1400€) vient de nous annoncer qu'il venait
# d'obtenir une promotion. Grâce à cette dernière, il a gagné 200€ sur son salaire mensuel.
# Effectuez cette modification au sein de votre array revenus.

print("Array avant:", revenus)
revenus[revenus == 1400] += 200
print("Array après:", revenus)

Array : [1800 1500 2200 3000 2172 5000 1400 1200 1100 1300]
Ensemble des revenus supérieurs ou égal à 3000€:  [3000 5000]
La somme des revenus annuelle est: 248064 €
La somme des revenus annuelle est: 248 K€
La somme des revenus annuelle est: 0.25 M€
La moyenne des revenus mensuelle est: 2067.2 €
Array avant: [1800 1500 2200 3000 2172 5000 1400 1200 1100 1300]
Array après: [1800 1500 2200 3000 2172 5000 1600 1200 1100 1300]


In [22]:
# Un tableau de 4 lignes et 3 colonnes rempli de 1
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# Un tableau de 4 lignes et de 4 colonnes contenant que des 0
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
# un tableau de 4 lignes et 3 colonnes rempli de valeurs aléatoires comprises entre 0 et 1
np.random.random((4, 3))

array([[0.41908681, 0.98319206, 0.29762875],
       [0.87377529, 0.06268155, 0.42912021],
       [0.26500671, 0.57081239, 0.69639389],
       [0.02475266, 0.54142051, 0.96826976]])

In [26]:
# un tableau de 3x3 rempli de valeurs aléatoires entières, comprises entre 1 et 10
np.random.randint(1, 10, size=(3, 5))

array([[5, 1, 4, 6, 3],
       [3, 1, 4, 6, 5],
       [6, 8, 9, 9, 3]])

In [28]:
# Transformer des donnees en tableaux
# L'ensemble des ces informations sont rassemblées dans la liste tableau suivante:

hugo = [1800, 21, 0]
richard = [1500, 54, 2]
emilie = [2200, 28, 3]
pierre = [3000, 37, 1]
paul = [2172, 37, 2]
deborah = [5000, 32, 0]
yohann = [1400, 23, 0]
anne = [1200, 25, 1]
thibault = [1100, 19, 0]
emmanuel = [1300, 31, 2]

tableau = [hugo, richard, emilie, pierre, paul, deborah, yohann, anne, thibault, emmanuel]

# A partir de cette liste, créez un array que vous nommerez data :
data = np.array(tableau)

# Paul souhaiterait contracter un prêt immobilier, affichez les informations qui lui sont relatives.
# Pour rappel, Paul correspond à la 5ème ligne de nos données

print("Informations de Paul :")
print(data[4, :])
print("-")
print("Ses mensualités maximales sont de :", round(data[4, 0] * 0.35, 2), "€")

# Un nouveau client vient d'arriver, dont les informations sont les suivantes :
louise = [1900, 31, 1]

# Ajoutez ces informations à la suite de votre array data :
np.vstack((data, louise))

# Stockez enfin l'ensemble des informations de salaire de notre clientèle dans une variable revenus :
revenus = data[:, 0]
print(revenus)

Informations de Paul :
[2172   37    2]
-
Ses mensualités maximales sont de : 760.2 €
[1800 1500 2200 3000 2172 5000 1400 1200 1100 1300]


In [34]:
a = np.linspace(5, 10, 11)
print(a[-3:-1])
b = a[a % 2 == 0]
print(b)

[9.  9.5]
[ 6.  8. 10.]


In [36]:
da = np.array([[[1, 2],[4, 5]],
        [[6, 7],[8, 9]],
        [[10, 11],[12, 13]]])

print(da)

[[[ 1  2]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]


In [40]:
da.reshape([4, 1, 3])

array([[[ 1,  2,  4]],

       [[ 5,  6,  7]],

       [[ 8,  9, 10]],

       [[11, 12, 13]]])

In [42]:
da[2, :, :]

array([[10, 11],
       [12, 13]])

In [43]:
np.arange(0, 8, 1)

array([0, 1, 2, 3, 4, 5, 6, 7])